spring.application.name=auth-service

# Eureka Client Configuration
server.port=0
eureka.client.service-url.defaultZone=${CONFIG_SERVER_URL}
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

# Configuration SS
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION}
