spring.application.name=user-service

#Eureka Client Configuration
server.port=0
eureka.client.service-url.defaultZone=${CONFIG_SERVER_URL}

#Configuration BD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${BD_URL}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}
